import { TasksProvider } from '../app/context/TasksContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <TasksProvider>
        {children}
        </TasksProvider>  
        
        </body>
    </html>
  )
}
