GET http://localhost:3000/api/ciudades HTTP/1.1

###



GET http://localhost:3000/api/ciudades/3 HTTP/1.1

###

POST http://localhost:3000/api/ciudades HTTP/1.1
Content-Type: application/json

{
    "name":"Paraguay",
    "capital":"Asuncion",
    "currency":"Guaranies"
}

###

PUT http://localhost:3000/api/ciudades/3 HTTP/1.1
Content-Type: application/json

{
    "name":"Mexico",
    "capital":"Mex",
    "currency":"pesos mexicano"
}


###

DELETE http://localhost:3000/api/ciudades/3 HTTP/1.1